### ISSUE TITLE
Aprimoramento do README para Facilitar a Execução do Projecto

### ISSUE THREAD

**Issue by fernandogomesfg** [Thon20/ANALISE-METEORITOS#1]
Olá Éllython,

Primeiramente, gostaria de parabenizá-lo pelo incrível projeto. 
Ao revisar o seu repositório, notei que o **README** pode ser aprimorado para fornecer uma orientação mais clara sobre como os interessados podem executar o projeto em seus próprios ambientes. Acredito que uma **documentação** pode facilitar a participação de outros colaboradores.

**Comment by Thon20** [comment]
Olá Fernando, fico muito feliz que gostou do projeto, irei adicionar as instruções de execução do projeto no README na próxima atualização, muito obrigado pelas dicas.

**Comment by Thon20** [comment]
> Olá Éllython,
> 
> Primeiramente, gostaria de parabenizá-lo pelo incrível projeto. 
> Ao revisar o seu repositório, notei que o **README** pode ser aprimorado para fornecer uma orientação mais clara sobre como os interessados podem executar o projeto em seus próprios ambientes. Acredito que uma **documentação** pode facilitar a participação de outros colaboradores.

Olá Fernando, primeiramente fico muito feliz que gostou do projeto, irei adicionar as instruções de execução do projeto no README na próxima atualização do projeto, muito obrigado pelas dicas.
